# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    mkdir obj
    make coverage
  displayName: 'make'
- script: |
    gcovr -x > output.xml
  displayName: 'gcovr'
- task: PublishCodeCoverageResults@1
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: 'output.xml'
